version: '1.0.0'
services:
  bot:
    build: .
    ports:
      - "25565:25565"
    env_file:
      - .env
    stdin_open: true
    tty: true
    volumes:
      - ./data:/app/data  # Adjust volume mapping as needed
    restart: unless-stopped
